// <auto-generated />
using System;
using LMS_THPT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS_THPT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS_THPT.Models.BaiGiang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("BaiGiang", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.BaiNop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiTapId")
                        .HasColumnType("int");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("DuongDanFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocSinhId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayCham")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiTapId");

                    b.HasIndex("HocSinhId");

                    b.ToTable("BaiNop", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.BaiTap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiemToiDa")
                        .HasColumnType("int");

                    b.Property<DateTime>("HanNop")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("BaiTap", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.BinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaiGiangId")
                        .HasColumnType("int");

                    b.Property<int?>("BaiTapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiGiangId");

                    b.HasIndex("BaiTapId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("ParentId");

                    b.ToTable("DanhSachBinhLuan");
                });

            modelBuilder.Entity("LMS_THPT.Models.DangKyHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocSinhId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HocSinhId");

                    b.HasIndex("MonHocId");

                    b.ToTable("DangKyHoc", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.DiemSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("GiangVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HocSinhId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoaiDiem")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("HocSinhId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("DiemSo", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.Khoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenKhoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Khoi", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.LichHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaoVienId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LopId")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thu")
                        .HasColumnType("int");

                    b.Property<int>("TietHoc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("LopId");

                    b.HasIndex("MonHocId");

                    b.ToTable("LichHoc", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.Lop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaoVienChuNhiemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaKhoi")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienChuNhiemId");

                    b.HasIndex("MaKhoi");

                    b.ToTable("Lop", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.LopMonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaoVienId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LopId")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("LopId");

                    b.HasIndex("MonHocId");

                    b.ToTable("LopMonHoc", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiangVienId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KhoiId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucTieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("KhoiId");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.MonHocGiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LopId")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LopId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("MonHocId", "LopId")
                        .IsUnique()
                        .HasFilter("[LopId] IS NOT NULL");

                    b.ToTable("MonHocGiaoViens");
                });

            modelBuilder.Entity("LMS_THPT.Models.NguoiDung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenMon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LopId")
                        .HasColumnType("int");

                    b.Property<string>("MaHocSinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LopId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.TaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaiGiangId")
                        .HasColumnType("int");

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("KichThuocFile")
                        .HasColumnType("bigint");

                    b.Property<int>("LoaiTaiLieu")
                        .HasColumnType("int");

                    b.Property<int?>("MonHocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaiGiangId");

                    b.HasIndex("MonHocId");

                    b.ToTable("TaiLieu", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HienThi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDangId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDangId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("LMS_THPT.Models.YeuCauGiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChuAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiYeuCau")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiXuLyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiaoVien");

                    b.HasIndex("NguoiXuLyId");

                    b.ToTable("YeuCauGiaoVien");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMS_THPT.Models.BaiGiang", b =>
                {
                    b.HasOne("LMS_THPT.Models.MonHoc", "MonHoc")
                        .WithMany("BaiGiangs")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS_THPT.Models.BaiNop", b =>
                {
                    b.HasOne("LMS_THPT.Models.BaiTap", "BaiTap")
                        .WithMany("BaiNops")
                        .HasForeignKey("BaiTapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.NguoiDung", "HocSinh")
                        .WithMany("BaiNops")
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiTap");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("LMS_THPT.Models.BaiTap", b =>
                {
                    b.HasOne("LMS_THPT.Models.MonHoc", "MonHoc")
                        .WithMany("BaiTaps")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS_THPT.Models.BinhLuan", b =>
                {
                    b.HasOne("LMS_THPT.Models.BaiGiang", "BaiGiang")
                        .WithMany()
                        .HasForeignKey("BaiGiangId");

                    b.HasOne("LMS_THPT.Models.BaiTap", "BaiTap")
                        .WithMany()
                        .HasForeignKey("BaiTapId");

                    b.HasOne("LMS_THPT.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.BinhLuan", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentId");

                    b.Navigation("BaiGiang");

                    b.Navigation("BaiTap");

                    b.Navigation("NguoiDung");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LMS_THPT.Models.DangKyHoc", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", "HocSinh")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.MonHoc", "MonHoc")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("LMS_THPT.Models.DiemSo", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.NguoiDung", "HocSinh")
                        .WithMany()
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.MonHoc", "MonHoc")
                        .WithMany("DiemSos")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.NguoiDung", null)
                        .WithMany("DiemSos")
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("GiangVien");

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("LMS_THPT.Models.LichHoc", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LMS_THPT.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.MonHoc", "MonHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("LMS_THPT.Models.Lop", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", "GiaoVienChuNhiem")
                        .WithMany()
                        .HasForeignKey("GiaoVienChuNhiemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LMS_THPT.Models.Khoi", "Khoi")
                        .WithMany("Lops")
                        .HasForeignKey("MaKhoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVienChuNhiem");

                    b.Navigation("Khoi");
                });

            modelBuilder.Entity("LMS_THPT.Models.LopMonHoc", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LMS_THPT.Models.Lop", "Lop")
                        .WithMany("LopMonHocs")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.MonHoc", "MonHoc")
                        .WithMany("LopMonHocs")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("LMS_THPT.Models.MonHoc", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LMS_THPT.Models.Khoi", "Khoi")
                        .WithMany("MonHocs")
                        .HasForeignKey("KhoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("Khoi");
                });

            modelBuilder.Entity("LMS_THPT.Models.MonHocGiaoVien", b =>
                {
                    b.HasOne("LMS_THPT.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LMS_THPT.Models.MonHoc", "MonHoc")
                        .WithMany("MonHocGiaoViens")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.NguoiDung", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("LMS_THPT.Models.NguoiDung", b =>
                {
                    b.HasOne("LMS_THPT.Models.Lop", "Lop")
                        .WithMany("HocSinhs")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("LMS_THPT.Models.TaiLieu", b =>
                {
                    b.HasOne("LMS_THPT.Models.BaiGiang", "BaiGiang")
                        .WithMany("TaiLieus")
                        .HasForeignKey("BaiGiangId");

                    b.HasOne("LMS_THPT.Models.MonHoc", "MonHoc")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MonHocId");

                    b.Navigation("BaiGiang");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("LMS_THPT.Models.ThongBao", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", "NguoiDang")
                        .WithMany()
                        .HasForeignKey("NguoiDangId");

                    b.Navigation("NguoiDang");
                });

            modelBuilder.Entity("LMS_THPT.Models.YeuCauGiaoVien", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGiaoVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.NguoiDung", "NguoiXuLy")
                        .WithMany()
                        .HasForeignKey("NguoiXuLyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GiaoVien");

                    b.Navigation("NguoiXuLy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_THPT.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LMS_THPT.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS_THPT.Models.BaiGiang", b =>
                {
                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("LMS_THPT.Models.BaiTap", b =>
                {
                    b.Navigation("BaiNops");
                });

            modelBuilder.Entity("LMS_THPT.Models.BinhLuan", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("LMS_THPT.Models.Khoi", b =>
                {
                    b.Navigation("Lops");

                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("LMS_THPT.Models.Lop", b =>
                {
                    b.Navigation("HocSinhs");

                    b.Navigation("LopMonHocs");
                });

            modelBuilder.Entity("LMS_THPT.Models.MonHoc", b =>
                {
                    b.Navigation("BaiGiangs");

                    b.Navigation("BaiTaps");

                    b.Navigation("DangKyHocs");

                    b.Navigation("DiemSos");

                    b.Navigation("LichHocs");

                    b.Navigation("LopMonHocs");

                    b.Navigation("MonHocGiaoViens");

                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("LMS_THPT.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiNops");

                    b.Navigation("DangKyHocs");

                    b.Navigation("DiemSos");
                });
#pragma warning restore 612, 618
        }
    }
}
