SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;

DELETE FROM [MonHocGiaoViens];
DELETE FROM [LopMonHoc];
DELETE FROM [LichHoc];
DELETE FROM [BaiNop];
DELETE FROM [BaiTap];
DELETE FROM [TaiLieu];
DELETE FROM [BaiGiang];
DELETE FROM [DiemSo];
DELETE FROM [DangKyHoc];
DELETE FROM [DanhSachBinhLuan];
DELETE FROM [ThongBaos];
DELETE FROM [YeuCauGiaoVien];
DELETE FROM [MonHoc];
UPDATE [NguoiDung] SET [LopId] = NULL;
UPDATE [Lop] SET [GiaoVienChuNhiemId] = NULL;
DELETE FROM [Lop];
DELETE FROM [Khoi];
DELETE FROM [AspNetUserClaims];
DELETE FROM [AspNetUserRoles];
DELETE FROM [AspNetUserLogins];
DELETE FROM [AspNetUserTokens];
DELETE FROM [NguoiDung];
DELETE FROM [AspNetRoleClaims];
DELETE FROM [AspNetRoles];
DELETE FROM [__EFMigrationsHistory];
PRINT 'Database cleared successfully.';
